### PR TITLE
dcos-log bug fixes

### PR DESCRIPTION
**Pull request by darkonie**
- change log line format to `timestamp MESSAGE`
 - change use /download postfix to download logs with GET request
 - add `postfix` get parameter to let the user pass a postfix for log file
   (should be used to separate stdout from stderr)

### CODE REVIEW

**Comment by malnick** [comment]
LGTM as long as @pyronicide is ok with this updated change.

**Comment by malnick** [comment]
Also - I thought the log format was only in the UI not the backend? Is there a request to change this on the CLI too?

**Comment by pyronicide** [comment]
Changes sound mostly good. Some questions:

- Instead of hard coding the log line format, can we default to timestamp only and have some query params to ask for more? Let's do that in a separate PR if it makes sense.
- I don't understand the `postfix` bit?

**Comment by darkonie** [comment]
@pyronicide postfix is a get parameter UI will use to add a postfix to a filename.

UI will pass the parameter ?postfix=stdout, and the filename to download will be `contianer_id-stdout.log`

**Pull request merged**
